DATA STRUCTURES, FUNCTIONS, NUMPY & PANDAS

SECTION A: DATA STRUCTURES AND CONTROL STRUCTURES

 1. Create a list of 5 integers. 
    Perform and print the result of the following operations: 
    append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [2]:
# Creating a list of 5 integers.
nums1 = [10, 20, 30, 40, 50]
print(nums1)

# append(value)
nums1.append(60) # It adds an element to the last index of the list.
print(nums1)

# extend([values])
nums1.extend([70, 80]) # It add an multiple elements to the end of the list.
print(nums1)

# insert(index, value)
nums1.insert(0, 5) # It adds an element to the 0th index.
print(nums1)

# remove(value)
nums1.remove(50) # It removes value from the list.
print(nums1)

# pop
nums1.pop() # It removes last index from the list.
print(nums1)

# index(value)
index_vlaue = nums1.index(60) # It gives value index from the list
print(index_vlaue)

# count
cnt = nums1.count(60) # It counts how many noof times the value occurs in the list.
print(cnt)

# reverse
nums1.reverse() # It will reverse the list.(Descending Order)
print(nums1)

# sort
nums1.sort() # It will sort the list.(Ascending Order)
print(nums1)

# clear
nums1.clear() # It removes all elements from the list.
print(nums1)

[10, 20, 30, 40, 50]
[10, 20, 30, 40, 50, 60]
[10, 20, 30, 40, 50, 60, 70, 80]
[5, 10, 20, 30, 40, 50, 60, 70, 80]
[5, 10, 20, 30, 40, 60, 70, 80]
[5, 10, 20, 30, 40, 60, 70]
5
1
[70, 60, 40, 30, 20, 10, 5]
[5, 10, 20, 30, 40, 60, 70]
[]


2.	Create a tuple that stores 3 student names. 
    Try changing the second name in the tuple. What happens? Explain why.

In [6]:
# Creating tuple.
student_Names = ("Tarun", "Mohith", "koushik")
print(student_Names)

# Changing the second name in the tuple.
student_Names[1] = "Krishna"

('Tarun', 'Mohith', 'koushik')


TypeError: 'tuple' object does not support item assignment

In [5]:
# What happens ?

"""
    -> Showing an error like "Tuple" object does not support item assignment.
"""

# Why ?

"""
    -> Because, Tuple is an Immutable. 
    -> Once tuple is created then we cannot modify, add or remove the elements.
    -> It is used for fixed data.
"""

'\n    -> Because, Tuple is an Immutable. \n    -> Once tuple is created then we cannot modify, add or remove the elements.\n    -> It is used for fixed data.\n'

3.	Create a set of integers with some duplicate values. 
    Print the set and explain the output.

In [8]:
# Creating set and printing the values.
int_Numbers = {10, 20, 30, 50, 20, 40, 20, 50, 30}
print(int_Numbers)

{50, 20, 40, 10, 30}


In [9]:
# Explanation of the output.

"""
    -> Duplicate values are not repeating in set.
    -> We can add or remove elements. But it does not allow duplicates.
"""

'\n    -> Duplicate values are not repeating in set.\n    -> We can add or remove elements. But it does not allow duplicates.\n'

4. Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. 
     Print the final dictionary.

In [11]:
# Creating a dictionary.
details = {
    'name' : "Tarun",
    'age' : 21,
    'city' : "Rajampet"
}
print(details)

# updating the age.
details['age'] = 22

# adding a new key 
details['email'] = "ptaruneswararao@gmail.com"

# Printing Final Dictionary.
print(details)

{'name': 'Tarun', 'age': 21, 'city': 'Rajampet'}
{'name': 'Tarun', 'age': 22, 'city': 'Rajampet', 'email': 'ptaruneswararao@gmail.com'}


  5. Write a script that checks if a person is eligible to vote (age ≥ 18).
     Take age as a variable and print the appropriate message.

In [13]:
# Asking user to enter his age.
age_Of_A_Person = int(input("Enter your age:"))

# Checking user is eligible for voting or not.
if (age_Of_A_Person >= 18):
    print("You are eligible to vote.")
else:
    print("You are not eligible to vote.")

Enter your age: 21


You are eligible to vote.


6. Given a 'marks' variable, print the grade:
    - 90 and above: 'A'
    - 75–89: 'B'
    - 50–74: 'C'
    - Below 50: 'Fail'

In [15]:
# Asking user to enter marks.
marks = int(input("Enter your marks:"))

# Cheking which grade user is getting.
if (marks >= 90):
    print("Grade A")
elif (marks >= 75):
    print("Grade B")
elif (marks >= 50):
    print("Grade c")
else:
    print("Fail")

Enter your marks: 99


Grade A


7.	Given a number, check if it's positive, and if it is also even.
        If not positive, print if it's zero or negative.

In [18]:
# Asking user to enter a number.
num = int(input("Enter a number:"))

# Checking positive or even positive or negative or zero.
if (num > 0):
    if (num % 2 == 0):
        print("It is Even Positive Number.")
    else:
        print("It is Positive Number.")
elif (num < 0):
    print("It is Negative Number.")
else:
    print("It is Zero.")

Enter a number: 24


It is Even Positive Number.


SECTION B: NUMPY

8. Create:
     - A scalar using np.array(5)
     - A 1D array with values 1 to 5
     - A 2D array (2x3) with values from 10 to 60 in steps of 10

In [1]:
import numpy as np

In [2]:
# Create a scalar.
scalar = np.array(5)
print(scalar)

# 1D Array
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)

# 2D Array
arr_2d = np.array([[10, 20, 30], [40, 50, 60]])
print(arr_2d)

5
[1 2 3 4 5]
[[10 20 30]
 [40 50 60]]


9. Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [3]:
import numpy as np

In [4]:
random_arr = np.random.randint(0, 101, size = (4, 4))
print(random_arr)

[[85 30 70 53]
 [16 87 47 64]
 [17  0 79 77]
 [ 7 84 57  4]]


10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [5]:
import numpy as np
import pandas as pd

In [6]:
# Creating 2D array.
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d)

# Converting into dataframe.
df = pd.DataFrame(arr_2d)
print(df)

# adding columns names.
df.columns = ['A', 'B', 'C']
print(df)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


Section C: EXPLORING PANDAS

11. Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
        - Use .info(), .describe()
        - Select 'Name' and 'City' columns
        - Drop 'City' column
        - Fill any missing values in 'Salary' column with the mean
        - Remove any duplicate rows

In [7]:
import numpy as np
import pandas as pd

In [8]:
# Creating a DataFrame.
data = {
    'Name' : ['Tarun', 'Sonu', 'Mohith', 'Tarun', 'Krishna', 'Radha', 'Rama', 'Seetha', 'Shiva', 'Parvathi'],
    'Age' : [21, 22, 21, 21, 35, 32, 54, 53, 73, 70],
    'City' : ['Rajampet', 'Bangarupalyam', 'Nellore', 'Rajampet', 'Dwaraka', 'Dwaraka', 'Tirupati', 'Arunachalam', 'Kaasi', 'Kailasam'],
    'Salary' : [15000, np.nan, 20000, 15000, np.nan, 50000, 60000, 70000, 80000, 90000]
}

df1 = pd.DataFrame(data)
df1

Name  Age           City   Salary
0     Tarun   21       Rajampet  15000.0
1      Sonu   22  Bangarupalyam      NaN
2    Mohith   21        Nellore  20000.0
3     Tarun   21       Rajampet  15000.0
4   Krishna   35        Dwaraka      NaN
5     Radha   32        Dwaraka  50000.0
6      Rama   54       Tirupati  60000.0
7    Seetha   53    Arunachalam  70000.0
8     Shiva   73          Kaasi  80000.0
9  Parvathi   70       Kailasam  90000.0

In [9]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [10]:
df1.describe()

Age        Salary
count  10.000000      8.000000
mean   40.200000  50000.000000
std    20.681715  30118.812346
min    21.000000  15000.000000
25%    21.250000  18750.000000
50%    33.500000  55000.000000
75%    53.750000  72500.000000
max    73.000000  90000.000000

In [11]:
# Selecting columns.
df1[['Name', 'City']]

Name           City
0     Tarun       Rajampet
1      Sonu  Bangarupalyam
2    Mohith        Nellore
3     Tarun       Rajampet
4   Krishna        Dwaraka
5     Radha        Dwaraka
6      Rama       Tirupati
7    Seetha    Arunachalam
8     Shiva          Kaasi
9  Parvathi       Kailasam

In [12]:
# Droping column.
df2 = df1.drop(columns = ['City'])
df2

Name  Age   Salary
0     Tarun   21  15000.0
1      Sonu   22      NaN
2    Mohith   21  20000.0
3     Tarun   21  15000.0
4   Krishna   35      NaN
5     Radha   32  50000.0
6      Rama   54  60000.0
7    Seetha   53  70000.0
8     Shiva   73  80000.0
9  Parvathi   70  90000.0

In [15]:
# Finding any missing values
print('Missing Values in Salary column:', df2["Salary"].isnull().sum())

# Finding mean for salary column.
salary_Mean = df2['Salary'].mean()

# Filling mean for missing values in salary column.
df2['Salary'].fillna(salary_Mean, inplace = True)
df2

Missing Values in Salary column: 0


C:\Users\ptaru\AppData\Local\Temp\ipykernel_30820\1285924841.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['Salary'].fillna(salary_Mean, inplace = True)


Name  Age   Salary
0     Tarun   21  15000.0
1      Sonu   22  50000.0
2    Mohith   21  20000.0
4   Krishna   35  50000.0
5     Radha   32  50000.0
6      Rama   54  60000.0
7    Seetha   53  70000.0
8     Shiva   73  80000.0
9  Parvathi   70  90000.0

In [14]:
# Removing duplicate rows in dataframe.
df2.drop_duplicates(inplace = True)
df2

Name  Age   Salary
0     Tarun   21  15000.0
1      Sonu   22  50000.0
2    Mohith   21  20000.0
4   Krishna   35  50000.0
5     Radha   32  50000.0
6      Rama   54  60000.0
7    Seetha   53  70000.0
8     Shiva   73  80000.0
9  Parvathi   70  90000.0